### ISSUE TITLE
添加配置 hugo 命令地址的选项

### ISSUE THREAD

**Issue by kahosense** [fzdwx/hugo-preview-obsidian#1]
hugo exec error: Command failed: hugo server -D -p 1313
bin sh: hugo: command not found

你好，我是在后台自己运行 hugo server再使用插件的。
hugo的预览功能能使用，但在使用中常出现上面的错误提示，是否有什么方法解决？
<img width="294" alt="Screenshot 2023-03-02 at 11 48 02" src="https://user-images.githubusercontent.com/107840660/222326709-2822ee39-7453-4136-8654-226e58ad3ea9.png">

**Comment by fzdwx** [comment]
你是啥系统？

**Comment by fzdwx** [comment]
就是找不到 hugo 命令的意思

**Comment by kahosense** [comment]
> 

mac 系统 13.0.1

**Comment by fzdwx** [comment]
`where hugo`

**Comment by kahosense** [comment]
> 

我知道找不到hugo命令的意思，但又没有设置选项。虽然不影响预览的功能，只是看有没有方法解决一下。解决不了也没关系。

**Comment by fzdwx** [comment]
ok, 这个星期我加一下配置选项

**Comment by fzdwx** [comment]
0.1.4 添加了
