### ISSUE TITLE
现在是无法执行hugo server这个命令吗

### ISSUE THREAD

**Issue by bfcs** [fzdwx/hugo-preview-obsidian#3]
我在macos上，hugo server这个命令一直报错

**Comment by fzdwx** [comment]
你安装了 `hugo` 了吗？ 如果是找不到可以在配置里面设置命令的全路径

**Comment by bfcs** [comment]
> 你安装了 `hugo` 了吗？ 如果是找不到可以在配置里面设置命令的全路径

和路径无关，应该是和exec这个函数有关，但是log没有任何有价值的信息
<img width="319" alt="image" src="https://github.com/fzdwx/hugo-preview-obsidian/assets/52602045/fe2237c6-8ea9-4d4e-9cdd-f9888e2a1b39">

**Comment by bfcs** [comment]
在命令行是可以执行成功的

**Comment by fzdwx** [comment]
代码在这 https://github.com/fzdwx/hugo-preview-obsidian/blob/main/src/cmd.ts#L21 晚点我自己试试

**Comment by bfcs** [comment]
可以的

**Comment by fzdwx** [comment]
我刚刚试了，没问题

**Comment by fzdwx** [comment]
复现的仓库有没有，发出来我试试
