### ISSUE TITLE
Option to add custom flags to hugo server

### ISSUE THREAD

**Issue by bep** [fzdwx/hugo-preview-obsidian#4]
Most notably I suspect `-N` (navigate to changed) would be a good default-

**Comment by fzdwx** [comment]
`-N` maybe is a not good default flag, it is not supported in older versions.

**Comment by bep** [comment]
>-N maybe is a not good default flag, it is not supported in older versions.

OK, `--navigateToChanged` has been there "forever".

**Comment by fzdwx** [comment]
You can upgrade plugin, it's there waiting for you. :)
